/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jplay_gdx_joypad_GamepadJniWrapper */

#ifndef _Included_com_jplay_gdx_joypad_GamepadJniWrapper
#define _Included_com_jplay_gdx_joypad_GamepadJniWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jplay_gdx_joypad_GamepadJniWrapper
 * Method:    natInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jplay_gdx_joypad_GamepadJniWrapper_natInit
  (JNIEnv *, jobject);

/*
 * Class:     com_jplay_gdx_joypad_GamepadJniWrapper
 * Method:    natRelease
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jplay_gdx_joypad_GamepadJniWrapper_natRelease
  (JNIEnv *, jobject);

/*
 * Class:     com_jplay_gdx_joypad_GamepadJniWrapper
 * Method:    natGetNumberOfPads
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jplay_gdx_joypad_GamepadJniWrapper_natGetNumberOfPads
  (JNIEnv *, jobject);

/*
 * Class:     com_jplay_gdx_joypad_GamepadJniWrapper
 * Method:    natDetectPads
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jplay_gdx_joypad_GamepadJniWrapper_natDetectPads
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
